[package]
name = "cheatz"
version = "0.1.0"
authors = ["adamc <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = "1.0.63"
cheatlib = { path = "cheatlib"}
log = "0.4.17"